version: 2.1
orbs:
  win: circleci/windows@5.1.0
jobs:
  build:
    executor: win/server-2022
    parameters:
      platform:
        type: enum
        enum: [x64, x86, arm64]
    steps:
      - checkout
      - run:
          name: "Clone repo"
          command: "git clone https://github.com/pbatard/rufus"
      - run:
          name: Build project
          command: |
            cd rufus
            msbuild rufus.sln -property:Configuration=Release,Platform=<< parameters.platform >>
      - run:
          name: Pack binary
          command: |
            7z a rufus-<< parameters.platform >>.7z .\rufus\<< parameters.platform >>\Release\rufus.exe
      - run:
          name: Upload artifact
          shell: pwsh.exe
          command: |
            $PSVersionTable
            $form = @{
                packageName  = 'rufus'
                packageVersion   = 'latest'
                packageFiles     = Get-Item -Path 'rufus-<< parameters.platform >>.7z'
            }
            $headers = @{
              "Authorization" = "Bearer $env:REPOFLOW_PAT"
            }
            Invoke-WebRequest -Uri $env:REPOFLOW_URL -Headers $headers -Method Post -Form $form
workflows:
  build-matrix:
    jobs:
      - build:
          matrix:
            parameters:
              platform: [x64, x86, arm64]
